manifest = "f754af443f4646c322481045715e1703325c1daf4d8e6ab53f791836bb0e9f86"

[[dependency]]
package = "github.com/buckaroo-pm/boost-concept_check"
target = "//:concept-check"

[[dependency]]
package = "github.com/buckaroo-pm/boost-integer"
target = "//:integer"

[[dependency]]
package = "github.com/buckaroo-pm/boost-logic"
target = "//:logic"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "branch=master" ]
revision = "f9d6a7b63ef2902777b6078fdebc54e7a57aac03"

[lock."github.com/buckaroo-pm/boost-concept_check"]
versions = [ "branch=master" ]
revision = "4dcd765d7933cb9419d9120cbf8df7d83e38f9db"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "branch=master" ]
revision = "4392ed19b232ed2dde7623843d7e30ef669d860e"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "branch=master" ]
revision = "4f59c5f06f11cd029a85d932ef51b9d511761f49"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "branch=master" ]
revision = "e8b834a93f7ba935aa63a3d6690804f3bd2b0963"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "branch=master" ]
revision = "5badcf5b232a15e89d0701bef687ffbe70398696"

[lock."github.com/buckaroo-pm/boost-logic"]
versions = [ "branch=master" ]
revision = "9cfeb22c998a09ab2133714848ea8a64c2b910c0"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "branch=master" ]
revision = "6493fcda0f5cd2ee595346ca48ff495db9fa74d5"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "branch=master" ]
revision = "a70772bbd315eb597c3f1e359af742dde46a6f37"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "branch=master" ]
revision = "fdc2df7f811436674a1c55c766b8830a8cd02e96"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "branch=master" ]
revision = "4d0a507c0d1a1011c5a98d57acc9f6b755141e4f"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "branch=master" ]
revision = "57aa216434800315c9cd2664169e444e3070a677"
